name: yuki-no

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch: # Manual trigger (Optional)

jobs:
  yuki-no:
    runs-on: ubuntu-latest
    steps:
      - uses: Gumball12/yuki-no@v1
        with:
          # GitHub access token. Required.
          access-token: ${{ secrets.GITHUB_TOKEN }}

          # The head repo to track. This is the repository you want to
          # take a diff. Required.
          head-repo: https://github.com/vitejs/vite.git

          # The git commit sha of head repo to start tracking. Yuki-no will
          # only track commit from this hash. Required.
          track-from: d444d6a113beeeb0e9d73ff157d83c45360d5699

          # List of file patterns to track. Multiple patterns can be specified
          # with newlines. Files matching these Glob patterns will be included
          # in tracking.
          # Glob Pattern: https://github.com/micromatch/picomatch?tab=readme-ov-file#advanced-globbing
          # If empty, all files will be tracked. Optional.
          include: |
            docs/**

          # Whether to enable release tracking.
          # When enabled, Yuki-no will track releases for each issue
          # and add comments about release status. Optional.
          # Defaults to 'false'
          release-tracking: true