name: ryu-cho

on:
  workflow_dispatch:

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-translations/ryu-cho@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          username: github-actions
          email: "action@github.com"
          upstream-repo: https://github.com/Gumball12/vite-docs-ja-with-yuki-no.git
          upstream-repo-branch: main
          head-repo: https://github.com/vitejs/vite
          head-repo-branch: main
          track-from: d444d6a113beeeb0e9d73ff157d83c45360d5699
          path-starts-with: docs/
          workflow-name: ryu-cho
